src: ./src/
site: ./development/

scripts:
    -
        src: index.js
        folder: /
        dest: static/js/
        filename: scripts.js

styles:
    -
        src:
            - style.styl
        dest: static/css/

favicons:
    src: favicons/
    dest: static/favicons/
    type:
        -
            name: apple-touch-icon
            ext: .png
            sizes: [16, 32, 96, 160, 192]
        -
            name: favicon
            ext: .png
            sizes: [57, 60, 72, 76, 114, 120, 144, 152, 180]
        -
            name: ms-tile
            ext: .png
            sizes: [144]

sprites:
    -
        type: png
        src:
            - sprite/png/**/*.png
        dest: static/img/sprite
        imgPath: ../img/sprite
        cssDest: css/
        filename: sprite.png
        stylename: sprite.styl
    -
        type: svg
        src:
            - sprite/svg/**/*.svg
        dest: /
        filename: icons.php
    -
        type: svg
        src:
            - sprite/svg-no-transform/**/*.svg
        dest: /
        filename: icons-no-transform.php
        transform: false
    -
        type: frames
        src:
            - sprite/frames/
        dest: static/medias/illustrations
